"use client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Button } from "./ui/Button";
const enter = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };
export function Hero() { const reduce = useReducedMotion(); return <section id="home" className="hero"><div className="hero-grid"/><div className="container hero-inner"><motion.div className="hero-copy" initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.12}}}}><motion.p variants={enter} className="hero-badge"><span/>MALDIVES-BASED · SERVING CLIENTS WORLDWIDE</motion.p><motion.h1 variants={enter}>Software &amp; Audio Video <span>Solutions That Deliver.</span></motion.h1><motion.p variants={enter} className="hero-description">We build reliable custom software, mobile applications and professional audio video solutions—designed for clear communication and lasting results.</motion.p><motion.div variants={enter} className="hero-actions"><a href="#contact"><Button arrow>Start a Project</Button></a><a href="#services" className="text-button">Explore Services <ArrowDown size={16}/></a></motion.div><motion.div variants={enter} className="hero-tags">{["Software", "Mobile Apps", "Audio Video", "Worldwide"].map(x => <span key={x}><CheckCircle2 size={14}/>{x}</span>)}</motion.div></motion.div><HeroVisual reduce={!!reduce}/></div></section> }
function HeroVisual({reduce}:{reduce:boolean}) {
 const float: any = reduce ? {} : { y: [0,-12,0], transition:{duration:5,repeat:Infinity,ease:"easeInOut"} };
 const planning: any = reduce ? {} : { y:[0,9,0], transition:{duration:4.3,repeat:Infinity,ease:"easeInOut"} };
 return <motion.div className="hero-visual" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.1}}><div className="orb"/><div className="visual-grid"/><motion.div className="float-card potential" animate={float}><strong>24/7</strong><span>Global Support</span><i/></motion.div><motion.div className="float-card planning" animate={planning}><div className="mini-icon">✦</div><span>Built to Perform</span><ArrowUpRight size={17}/></motion.div><motion.div className="float-card satisfaction" animate={float}><strong>100%</strong><span>Secure Delivery</span></motion.div><span className="dot dot-one"/><span className="dot dot-two"/><svg className="visual-line" viewBox="0 0 500 420" aria-hidden="true"><path d="M20 320 C120 280 200 350 270 220 S390 160 480 60" fill="none"/><circle cx="270" cy="220" r="5"/></svg></motion.div>;
}
